### ISSUE TITLE
Feature Request: define on/off times 

### ISSUE THREAD

**Issue by ojaatka** [mightymartin/wordclock_esp8266#4]
Hi,

hope it is allowed to ask for features here.

It would be nice if the wordclock can be switched ob by night
e.G from 00:00 to 06:00 in my case

**Comment by mightymartin** [comment]
Hi,

of course it is! I was planning to implement some new features on christmas holiday, so chances will be good.

i am thinking of some classic "notch in"-timer design, so you can check the on-time-hours of the day. (eg 000000001111111111110000 is 8am to 8pm) 

regards
Martin

**Comment by ojaatka** [comment]
Great, thanks for that.
I'm using HomeAssistant meanwhile I'm going to look at the MQTT interface.
Possibly I can also use an automation to do this.

**Comment by mightymartin** [comment]
Hi,

there is an auto on/off feature now. it switches the clock on or off to the given times, so you are able to do it manually in the mean time.

**Comment by ojaatka** [comment]
Thanks!
