### ISSUE TITLE
Wordcklock von Ulrich Radig lebt

### ISSUE THREAD

**Issue by dbambus** [mightymartin/wordclock_esp8266#5]
Hallo @mightymartin,

ich bin grade auf dein Projekt hier auf Github gestoßen und habe deine Übersicht der Wordclock Varianten gesehen. Hier wollte ich nur ergänzen, dass ich den Code von Ulrich Radig aktiv weiterentwickle :-). 

Wird doch mal einen Blick auf https://github.com/dbambus/Worduhr :-)

**Comment by mightymartin** [comment]
Hi,Danke für den Hinweis. Bei der Radig Variante hab ich nur aufgenommen, damit ich die als alternative zu der Spaghetti-Code Software in Forum stellen konnte. Die Neuimplementierung hat mich weniger zeit gekostet als das Anpassen ;) Zumal die Entwicklung Stile auch auseinander laufen :)VGMartinAm 08.01.2021 09:42 schrieb dbambus <notifications@github.com>:

Hallo @mightymartin,

ich bin grade auf dein Projekt hier auf Github gestoßen und habe deine Übersicht der Wordclock Varianten gesehen. Hier wollte ich nur ergänzen, dass ich den Code von Ulrig Radig aktiv weiterentwickle :-).

Wird doch mal einen Blick auf https://github.com/dbambus/Worduhr :-)
